If LCase(Right(Wscript.FullName, 11)) = "wscript.exe" Then

    strPath = Wscript.ScriptFullName

    strCommand = "%comspec% /k cscript  " & Chr(34) & strPath & chr(34)

    Set objShell = CreateObject("Wscript.Shell")

    objShell.Run(strCommand)

    Wscript.Quit

End If

 

 

set wsc = CreateObject("WScript.Shell")

Do

                wsc.SendKeys ("{SCROLLLOCK}")

                WScript.Sleep (6*1000)

                wsc.SendKeys ("{SCROLLLOCK}")

                WScript.Sleep (60*1000)

Loop

'' SIG '' Begin signature block
'' SIG '' MIIXowYJKoZIhvcNAQcCoIIXlDCCF5ACAQExCzAJBgUr
'' SIG '' DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
'' SIG '' gjcCAR4wJAIBAQQQTvApFpkntU2P5azhDxfrqwIBAAIB
'' SIG '' AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFLlh14dUFinh
'' SIG '' hCTIsaA80hYynGmRoIITjjCCA+4wggNXoAMCAQICEH6T
'' SIG '' 6/t8xk5Z6kuad9QG/DswDQYJKoZIhvcNAQEFBQAwgYsx
'' SIG '' CzAJBgNVBAYTAlpBMRUwEwYDVQQIEwxXZXN0ZXJuIENh
'' SIG '' cGUxFDASBgNVBAcTC0R1cmJhbnZpbGxlMQ8wDQYDVQQK
'' SIG '' EwZUaGF3dGUxHTAbBgNVBAsTFFRoYXd0ZSBDZXJ0aWZp
'' SIG '' Y2F0aW9uMR8wHQYDVQQDExZUaGF3dGUgVGltZXN0YW1w
'' SIG '' aW5nIENBMB4XDTEyMTIyMTAwMDAwMFoXDTIwMTIzMDIz
'' SIG '' NTk1OVowXjELMAkGA1UEBhMCVVMxHTAbBgNVBAoTFFN5
'' SIG '' bWFudGVjIENvcnBvcmF0aW9uMTAwLgYDVQQDEydTeW1h
'' SIG '' bnRlYyBUaW1lIFN0YW1waW5nIFNlcnZpY2VzIENBIC0g
'' SIG '' RzIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
'' SIG '' AQCxrLNJVEuXHBIK2CV5kSJXKm/cuCbEQ3Nrwr8uUFr7
'' SIG '' FMJ2jkMBJUO0oeJF9Oi3e8N0zCLXtJQAAvdN7b+0t0Qk
'' SIG '' a81fRTvRRM5DEnMXgotptCvLmR6schsmTXEfsTHd+1Fh
'' SIG '' AlOmqvVJLAV4RaUvic7nmef+jOJXPz3GktxK+Hsz5HkK
'' SIG '' +/B1iEGc/8UDUZmq12yfk2mHZSmDhcJgFMTIyTsU2sCB
'' SIG '' 8B8NdN6SIqvK9/t0fCfm90obf6fDni2uiuqm5qonFn1h
'' SIG '' 95hxEbziUKFL5V365Q6nLJ+qZSDT2JboyHylTkhE/xni
'' SIG '' RAeSC9dohIBdanhkRc1gRn5UwRN8xXnxycFxAgMBAAGj
'' SIG '' gfowgfcwHQYDVR0OBBYEFF+a9W5czMx0mtTdfe8/2+xM
'' SIG '' gC7dMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcwAYYW
'' SIG '' aHR0cDovL29jc3AudGhhd3RlLmNvbTASBgNVHRMBAf8E
'' SIG '' CDAGAQH/AgEAMD8GA1UdHwQ4MDYwNKAyoDCGLmh0dHA6
'' SIG '' Ly9jcmwudGhhd3RlLmNvbS9UaGF3dGVUaW1lc3RhbXBp
'' SIG '' bmdDQS5jcmwwEwYDVR0lBAwwCgYIKwYBBQUHAwgwDgYD
'' SIG '' VR0PAQH/BAQDAgEGMCgGA1UdEQQhMB+kHTAbMRkwFwYD
'' SIG '' VQQDExBUaW1lU3RhbXAtMjA0OC0xMA0GCSqGSIb3DQEB
'' SIG '' BQUAA4GBAAMJm495739ZMKrvaLX64wkdu0+CBl03X6ZS
'' SIG '' nxaN6hySCURu9W3rWHww6PlpjSNzCxJvR6muORH4KrGb
'' SIG '' sBrDjutZlgCtzgxNstAxpghcKnr84nodV0yoZRjpeUBi
'' SIG '' JZZux8c3aoMhCI5B6t3ZVz8dd0mHKhYGXqY4aiISo1EZ
'' SIG '' g362MIIEozCCA4ugAwIBAgIQDs/0OMj+vzVuBNhqmBsa
'' SIG '' UDANBgkqhkiG9w0BAQUFADBeMQswCQYDVQQGEwJVUzEd
'' SIG '' MBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xMDAu
'' SIG '' BgNVBAMTJ1N5bWFudGVjIFRpbWUgU3RhbXBpbmcgU2Vy
'' SIG '' dmljZXMgQ0EgLSBHMjAeFw0xMjEwMTgwMDAwMDBaFw0y
'' SIG '' MDEyMjkyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMR0wGwYD
'' SIG '' VQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjE0MDIGA1UE
'' SIG '' AxMrU3ltYW50ZWMgVGltZSBTdGFtcGluZyBTZXJ2aWNl
'' SIG '' cyBTaWduZXIgLSBHNDCCASIwDQYJKoZIhvcNAQEBBQAD
'' SIG '' ggEPADCCAQoCggEBAKJjCzlEuLsjp0RJuw7/ofBhClOT
'' SIG '' sJjbrSwPSsVu/4Y8U1UPFc4EPyv9qZaW2b5heQtbyUyG
'' SIG '' duXgQ0sile7CK0PBn9hotI5AT+6FOLkRxSPyZFjwFTJv
'' SIG '' TlehroikAtcqHs1L4d1j1ReJMluwXplaqJ0oUA4X7pbb
'' SIG '' YTtFUR3PElYLkkf8q672Zj1HrHBy55LnX80QucSDZJQZ
'' SIG '' vSWA4ejSIqXQugJ6oXeTW2XD7hd0vEGGKtwITIySjJEt
'' SIG '' nndEH2jWqHR32w5bMotWizO92WPISZ06xcXqMwvS8aMb
'' SIG '' 9Iu+2bNXizveBKd6IrIkri7HcMW+ToMmCPsLvalPmQjh
'' SIG '' EChyqs0CAwEAAaOCAVcwggFTMAwGA1UdEwEB/wQCMAAw
'' SIG '' FgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/
'' SIG '' BAQDAgeAMHMGCCsGAQUFBwEBBGcwZTAqBggrBgEFBQcw
'' SIG '' AYYeaHR0cDovL3RzLW9jc3Aud3Muc3ltYW50ZWMuY29t
'' SIG '' MDcGCCsGAQUFBzAChitodHRwOi8vdHMtYWlhLndzLnN5
'' SIG '' bWFudGVjLmNvbS90c3MtY2EtZzIuY2VyMDwGA1UdHwQ1
'' SIG '' MDMwMaAvoC2GK2h0dHA6Ly90cy1jcmwud3Muc3ltYW50
'' SIG '' ZWMuY29tL3Rzcy1jYS1nMi5jcmwwKAYDVR0RBCEwH6Qd
'' SIG '' MBsxGTAXBgNVBAMTEFRpbWVTdGFtcC0yMDQ4LTIwHQYD
'' SIG '' VR0OBBYEFEbGaaMOShQe1UzaUmMXP142vA3mMB8GA1Ud
'' SIG '' IwQYMBaAFF+a9W5czMx0mtTdfe8/2+xMgC7dMA0GCSqG
'' SIG '' SIb3DQEBBQUAA4IBAQB4O7SRKgBM8I9iMDd4o4QnB28Y
'' SIG '' st4l3KDUlAOqhk4ln5pAAxzdzuN5yyFoBtq2MrRtv/Qs
'' SIG '' JmMz5ElkbQ3mw2cO9wWkNWx8iRbG6bLfsundIMZxD82V
'' SIG '' dNy2XN69Nx9DeOZ4tc0oBCCjqvFLxIgpkQ6A0RH83Vx2
'' SIG '' bk9eDkVGQW4NsOo4mrE62glxEPwcebSAe6xp9P2ctgwW
'' SIG '' K/F/Wwk9m1viFsoTgW0ALjgNqCmPLOGy9FqpAa8VnCwv
'' SIG '' SRvbIrvD/niUUcOGsYKIXfA9tFGheTMrLnu53CAJE3Hr
'' SIG '' ahlbz+ilMFcsiUk/uc9/yb8+ImhjU5q9aXSsxR08f5Lg
'' SIG '' w7wc2AR1MIIFbjCCA1agAwIBAgITGAAAAE87vt7sD67K
'' SIG '' ngACAAAATzANBgkqhkiG9w0BAQsFADBCMRMwEQYKCZIm
'' SIG '' iZPyLGQBGRYDQ09NMRUwEwYKCZImiZPyLGQBGRYFRk5G
'' SIG '' SVMxFDASBgNVBAMTC0ZORklTUk9PVENBMB4XDTIwMDUy
'' SIG '' NzIwMjYwMVoXDTMzMDUyNzIwMzYwMVowQzETMBEGCgmS
'' SIG '' JomT8ixkARkWA2NvbTEVMBMGCgmSJomT8ixkARkWBUZO
'' SIG '' RklTMRUwEwYDVQQDEwxTR0FGSVNDRVJUMDIwggEiMA0G
'' SIG '' CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCg03iLM8GV
'' SIG '' HuXxZIqKnN4/ztHBql/7WOHHBX7VWfGf6mKocXSHlZrX
'' SIG '' BDuYsV/VpikZic3SCi/hCnAaIAbc7TXjQnFPD7SsHUG7
'' SIG '' xPyOvb/gdIFBGtBc+Qanr8eXM4ja6EYYz34ihPKI62P9
'' SIG '' sr5zNw7r2AM9FEArMdvlNip2Jat6IYISn9eWHH2hgcPx
'' SIG '' L4jLCgPI01Dtg2lsl0KVCd8/Ga0qwfJJ37/JTR/L1V1h
'' SIG '' EQVWWeh/1OHFHg1SgnfeqhlW7v7bbrNAssNtrzFR+6Bj
'' SIG '' jGjT0IZbzPdZ/LoFPhFzE6wN1EpdJYtrks7+gD3SomGD
'' SIG '' rjAQcYfeHXKEQ54jxcF1h5ARAgMBAAGjggFaMIIBVjAS
'' SIG '' BgkrBgEEAYI3FQEEBQIDAgAEMCMGCSsGAQQBgjcVAgQW
'' SIG '' BBRxEKSCWsXrZG1zpxNzsZj6tU+lCDAdBgNVHQ4EFgQU
'' SIG '' Yx79nFFtS52MaKcFmukogbG6mLIwGQYJKwYBBAGCNxQC
'' SIG '' BAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1Ud
'' SIG '' EwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUCBHKHZW2cYvG
'' SIG '' YAwrloEU0BMoKRAwRAYDVR0fBD0wOzA5oDegNYYzZmls
'' SIG '' ZTovLy8vU0dBRklTQ0VSVDAxL0NlcnRFbnJvbGwvRk5G
'' SIG '' SVNST09UQ0EoMSkuY3JsMFwGCCsGAQUFBwEBBFAwTjBM
'' SIG '' BggrBgEFBQcwAoZAZmlsZTovLy8vU0dBRklTQ0VSVDAx
'' SIG '' L0NlcnRFbnJvbGwvU0dBRklTQ0VSVDAxX0ZORklTUk9P
'' SIG '' VENBKDIpLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAJI1z
'' SIG '' Mtx321tUd90tCGD3aW7M2tZDjvtJEHig30YHJkD5u33C
'' SIG '' 5qYVUEBflcKNW7D9/qsuYSCHjRXdnOu5FwqrzIGmWU90
'' SIG '' MhQ3nC+xRVoaL80A4vE9RiANTlAIED00CM2YedHgu3qU
'' SIG '' ud8jhHd+dzg8f49UBN2QNBt9XVggNwJLelGB1r7vNmQj
'' SIG '' 7JYfAS/a46AEPKZ6QFD5VZa7OJ5LAldbBK0qiU9XaR+X
'' SIG '' pN0mfoLgbBbVP7Fffec6slWSt0VZ84qHszyvZSPdY+tF
'' SIG '' XRatU0kvZvss+J/GoSU5DoNtsLgjhSNr/JEj0UbitZlu
'' SIG '' 8SswD8nb6rNfhpy/ihBx1hBf+KpFtHjwonte+nqYHMDH
'' SIG '' au1SMakCCs6RydKcXOaJKJNxwY6FA+LZmGg1W9j6lWF+
'' SIG '' Mvx6p/uBoRz9oN9/+kgz9uUanmoDeDyQlqAL4hQat4YN
'' SIG '' EHKKwnN+/iXY5LWXRsugm4RXPDLPmPnA5QnkFrByEpIg
'' SIG '' al1gVl2BnyQLftYbyN5SegyAPJo5M2rBAMAABJghv9D3
'' SIG '' 3qDeTJPVjMfFe5ppYdfJZwM+nGYhsZ7GaXXJZHR40WJX
'' SIG '' XkX4DwVvFWj/NR8z8JfHjdErjSjofDmMp3YZ1NXXVD3u
'' SIG '' VXcsLnYMBASCshvOhewtZT8RymSC98AdRxwqfWt6l16h
'' SIG '' Or5uubGZHSZStjukpYIwggV/MIIEZ6ADAgECAhMlAB/7
'' SIG '' pC3itRUjL5BpAAIAH/ukMA0GCSqGSIb3DQEBCwUAMEMx
'' SIG '' EzARBgoJkiaJk/IsZAEZFgNjb20xFTATBgoJkiaJk/Is
'' SIG '' ZAEZFgVGTkZJUzEVMBMGA1UEAxMMU0dBRklTQ0VSVDAy
'' SIG '' MB4XDTE3MDcyNTE4MzM0MloXDTIwMDcyNTE4NDM0Mlow
'' SIG '' UDETMBEGCgmSJomT8ixkARkWA2NvbTEVMBMGCgmSJomT
'' SIG '' 8ixkARkWBUZORklTMSIwIAYDVQQDExlGSVMtR2xvYmFs
'' SIG '' VGVzdGluZ1NlcnZpY2VzMIGfMA0GCSqGSIb3DQEBAQUA
'' SIG '' A4GNADCBiQKBgQDxoDalinv85wI5fWSDzf+yOhVKQutZ
'' SIG '' ft38WdBKiFj7h+IiogJlhuJ9kIAzjQbMht7Kqzy9c2vb
'' SIG '' WrvX6KkWFbyjaJWAGn7jH/23jrFj4idbV2d/G4dfOeIE
'' SIG '' OcHmfnd4syUbTGlsAfdV0YaRzIQ8esNiSjDJpGVuH83n
'' SIG '' wXj6p0SIYQIDAQABo4IC4TCCAt0wPQYJKwYBBAGCNxUH
'' SIG '' BDAwLgYmKwYBBAGCNxUIg47RaIKF6hKB4YcpgYzJVYeG
'' SIG '' xjkAhJX2GIa7kigCAWQCAQowEwYDVR0lBAwwCgYIKwYB
'' SIG '' BQUHAwMwCwYDVR0PBAQDAgeAMBsGCSsGAQQBgjcVCgQO
'' SIG '' MAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFJQfFuHFlzqK
'' SIG '' xAE/gCDedU4fF/5vMB8GA1UdIwQYMBaAFGMe/ZxRbUud
'' SIG '' jGinBZrpKIGxupiyMIIBAwYDVR0fBIH7MIH4MIH1oIHy
'' SIG '' oIHvhjFodHRwOi8vY2VydHNlcnYuZm5maXMuY29tL0NE
'' SIG '' UC9TR0FGSVNDRVJUMDIoMikuY3JshoG5bGRhcDovLy9D
'' SIG '' Tj1TR0FGSVNDRVJUMDIoMiksQ049U0dBRklTQ0VSVDAy
'' SIG '' LENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
'' SIG '' cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERD
'' SIG '' PUZORklTLERDPWNvbT9jZXJ0aWZpY2F0ZVJldm9jYXRp
'' SIG '' b25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJp
'' SIG '' YnV0aW9uUG9pbnQwggEUBggrBgEFBQcBAQSCAQYwggEC
'' SIG '' MFQGCCsGAQUFBzAChkhodHRwOi8vY2VydHNlcnYuZm5m
'' SIG '' aXMuY29tL0NEUC9TR0FGSVNDRVJUMDIuRk5GSVMuY29t
'' SIG '' X1NHQUZJU0NFUlQwMigyKS5jcnQwgakGCCsGAQUFBzAC
'' SIG '' hoGcbGRhcDovLy9DTj1TR0FGSVNDRVJUMDIsQ049QUlB
'' SIG '' LENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNl
'' SIG '' cnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9Rk5GSVMs
'' SIG '' REM9Y29tP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RD
'' SIG '' bGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MA0GCSqG
'' SIG '' SIb3DQEBCwUAA4IBAQBUrtivxlDF1fDrzReGSTi9Imv5
'' SIG '' 7pwthFwDzVq0NxJ424c+8VtVbhz2NLAdxndvo45ZoCZs
'' SIG '' jUL3RDZv5Wi1ikOAAiPU6X2LwQ9HfOBCKiiFEgPtlkWH
'' SIG '' u2rDBve8+TnIqh8bKMg7OjnkmQFPcdGK48U8vKYlQYTz
'' SIG '' O/RPo8MtkbPnrj7VIzgjR1UVqsAFxqneAfDZb6P/UbcN
'' SIG '' ywNn7jktTYdGaMNmfH1HNB5VKlRFR3BMDB2lyA3vgjEu
'' SIG '' kVwUMKipeayPTpUIc1z4ulYuY8aUTCBLl2pAZMknEyDf
'' SIG '' Az2U+mmZXukWUFTF2/0nz7HiPrPGMeXAtuWWkUsZkHS2
'' SIG '' ziNkVoaOMYIDgTCCA30CAQEwWjBDMRMwEQYKCZImiZPy
'' SIG '' LGQBGRYDY29tMRUwEwYKCZImiZPyLGQBGRYFRk5GSVMx
'' SIG '' FTATBgNVBAMTDFNHQUZJU0NFUlQwMgITJQAf+6Qt4rUV
'' SIG '' Iy+QaQACAB/7pDAJBgUrDgMCGgUAoHAwEAYKKwYBBAGC
'' SIG '' NwIBDDECMAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcC
'' SIG '' AQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUw
'' SIG '' IwYJKoZIhvcNAQkEMRYEFNl11eAO0KR9NHeB4sHkMvAO
'' SIG '' a/+OMA0GCSqGSIb3DQEBAQUABIGAMhT2WrTLilDNVH6D
'' SIG '' UBV4R03gpz8vj+mRHwW4GlRPDrQS7irG/dvvIGH0Tj8K
'' SIG '' 1mzM5wijAz0y1TWR+e/nqfQmszYWliFBcjyt5N7BW4Me
'' SIG '' 0u9J0//y5BU1BKTdCrBqg2T8+KX3jivFprBniOpC9C43
'' SIG '' L8HDZZAQvXJ415D120jZUsShggILMIICBwYJKoZIhvcN
'' SIG '' AQkGMYIB+DCCAfQCAQEwcjBeMQswCQYDVQQGEwJVUzEd
'' SIG '' MBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xMDAu
'' SIG '' BgNVBAMTJ1N5bWFudGVjIFRpbWUgU3RhbXBpbmcgU2Vy
'' SIG '' dmljZXMgQ0EgLSBHMgIQDs/0OMj+vzVuBNhqmBsaUDAJ
'' SIG '' BgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3
'' SIG '' DQEHATAcBgkqhkiG9w0BCQUxDxcNMjAwNzE2MTc0NDI2
'' SIG '' WjAjBgkqhkiG9w0BCQQxFgQUj5nxv/GqL9rzM1B3UBjW
'' SIG '' Dm6XS8EwDQYJKoZIhvcNAQEBBQAEggEATkTev1v2je29
'' SIG '' +UM3AocYwne/zDpiFDGbUDsQhk2rKlBa9bR3n+Zc2Gan
'' SIG '' 7aTfzG0V9l1wN2dcpZiaFvXmCs66XAMYIUdeBRO715CX
'' SIG '' AuThh9JGkCZIAvQpq8kNeoKbomX4qp15z9LJTSRnymXY
'' SIG '' CSv+QdxIGLR8vQJftCQWmsA6J9ISl54lhLX+qXQXm9DN
'' SIG '' FE+t+j99eWVMig2xjeg/pWFOXVOtq+Mi9/5tnn6AKSRi
'' SIG '' fAvbDNdfDPFure569WRFQ+aKtBs9/youqXs/KgKj4zm0
'' SIG '' JTqlkbZ3Hnv4mQysL7oEh5rDIMqnQMdooQMvsDgaX0D2
'' SIG '' G70OpQV3ADdgggDmA+ugzA==
'' SIG '' End signature block
